"""
Evaluation module for claims extraction pipeline.

Goal:
Measure how accurate the AI system is by comparing its predictions
with the ground truth (correct answers).

What this script does:
- Compares predicted vs real values field by field
- Computes accuracy for each field
- Computes overall accuracy
- Stores detailed errors for debugging

Important concept:
Each claim contains multiple fields,
so evaluation is done field by field, not only claim by claim.

Example:
100 claims × 4 fields = 400 total field comparisons
"""

import json   # Used to read input files and save evaluation errors as JSON


print("USING FILE: cleaned_claims.json")


# =========================
# LOAD DATA
# =========================
"""
Goal:
Load both predicted data and ground truth data.

Logic:
- predictions = output generated by the pipeline
- ground_truth = correct expected answers

Why important:
Evaluation only works if both sides exist:
- what the AI predicted
- what the correct answer should be

Example:
prediction → {"amount": 1200}
ground truth → {"amount": 1000}
"""

with open("data/processed/cleaned_claims.json", "r", encoding="utf-8") as f:
    predictions = json.load(f)

with open("ground_truth/ground_truth.json", "r", encoding="utf-8") as f:
    ground_truth = json.load(f)


# =========================
# DEBUG SAMPLE
# =========================
"""
Goal:
Verify the structure of both datasets before full evaluation.

Logic:
- Print the first item from each file

Why important:
This helps detect hidden problems early,
such as missing keys or unexpected formats.

Important assumption:
This block expects both lists to contain at least one element.
"""

print("\n--- DEBUG SAMPLE ---")
print("PREDICTION SAMPLE:", predictions[0])
print("GROUND TRUTH SAMPLE:", ground_truth[0])
print("---------------------\n")


# =========================
# LOOKUP TABLE
# =========================
"""
Goal:
Create fast access to ground truth records.

Logic:
- Convert the ground truth list into a dictionary
- Use doc_id as the key

Why useful:
Without this,
the script would need to loop through the full ground_truth list
for every single prediction.

That would be slower and less efficient.

Example:
gt_dict["doc_1"] → instantly returns the matching ground truth record
"""

gt_dict = {item["doc_id"]: item for item in ground_truth}


# =========================
# METRIC VARIABLES
# =========================
"""
Goal:
Track evaluation results.

Logic:
- Count how many times each field is correct
- Count how many claims were actually comparable
- Save mismatches for debugging

Important:
valid_samples means:
→ number of predictions that found a matching ground truth record

So if some predictions have no matching doc_id,
they are skipped and do not count in the final accuracy.
"""

correct_counts = {
    "customer_name": 0,
    "claim_date": 0,
    "claim_type": 0,
    "amount": 0
}

errors = []
valid_samples = 0


# =========================
# NORMALIZATION FUNCTIONS
# =========================
def normalize_text(value):
    """
    Goal:
    Normalize text before comparison.

    Logic:
    - Convert value to string
    - Remove extra spaces at the beginning or end
    - Convert to lowercase

    Why important:
    This avoids false mismatches caused only by formatting.

    Example:
    " John Doe " → "john doe"

    So:
    "John Doe" and " john doe "
    are treated as the same value
    """

    if value is None:
        return None

    return str(value).strip().lower()


def normalize_amount(value):
    """
    Goal:
    Normalize numeric values before comparison.

    Logic:
    - Try to convert the value into an integer
    - If conversion fails, return None

    Why important:
    Amount values may appear in different raw formats.
    This makes them easier to compare consistently.

    Example:
    "1200" → 1200
    1200 → 1200
    "abc" → None
    """

    try:
        return int(value)
    except:
        return None


# =========================
# MAIN COMPARISON LOOP
# =========================
"""
Goal:
Compare each predicted claim with its matching ground truth claim.

Logic:
1. Loop through predictions
2. Find the matching ground truth using doc_id
3. Compare each field
4. Record correct values and errors

Example:
prediction = {"amount": 1200}
ground truth = {"amount": 1000}
→ mismatch is recorded in errors
"""

for pred in predictions:

    doc_id = pred.get("doc_id")

    gt = gt_dict.get(doc_id)

    """
    If no matching ground truth is found:
    → skip this claim

    Why:
    Evaluation requires both a prediction and a correct reference.

    This prediction will not count in valid_samples.
    """
    if not gt:
        continue

    valid_samples += 1


    # =========================
    # TEXT FIELD COMPARISON
    # =========================
    """
    Goal:
    Compare text-based fields.

    Fields compared:
    - customer_name
    - claim_date
    - claim_type

    Logic:
    - Normalize both values
    - Compare normalized versions
    - Count correct results or store mismatch
    """

    for field in ["customer_name", "claim_date", "claim_type"]:

        pred_val = normalize_text(pred.get(field))
        gt_val = normalize_text(gt.get(field))

        if pred_val == gt_val:
            correct_counts[field] += 1
        else:
            errors.append({
                "doc_id": doc_id,
                "field": field,
                "predicted": pred_val,
                "expected": gt_val
            })


    # =========================
    # AMOUNT COMPARISON
    # =========================
    """
    Goal:
    Compare amount values.

    Logic:
    - Convert both values to integers
    - Compare them exactly

    Important:
    This is a strict comparison.
    There is no tolerance margin here.

    Example:
    1200 == 1200 → correct
    1200 != 1199 → incorrect
    """

    pred_amount = normalize_amount(pred.get("amount"))
    gt_amount = normalize_amount(gt.get("amount"))

    if pred_amount == gt_amount:
        correct_counts["amount"] += 1
    else:
        errors.append({
            "doc_id": doc_id,
            "field": "amount",
            "predicted": pred_amount,
            "expected": gt_amount
        })


# =========================
# CALCULATE RESULTS
# =========================

print("\nEVALUATION RESULTS\n")

"""
Goal:
Compute accuracy for each individual field.

Formula:
accuracy = (correct / total comparable samples) × 100

Example:
80 correct out of 100 valid samples
→ 80%
"""

for field, count in correct_counts.items():
    accuracy = (count / valid_samples) * 100 if valid_samples else 0
    print(f"{field}: {accuracy:.2f}%")


"""
Goal:
Compute overall accuracy across all fields.

Logic:
1. Add all correct predictions together
2. Divide by total number of possible field comparisons

Formula:
overall = total_correct / (valid_samples × number_of_fields)

Example:
100 claims × 4 fields = 400 possible comparisons
320 correct → 80%
"""

overall = (
    sum(correct_counts.values()) /
    (valid_samples * len(correct_counts))
    * 100
    if valid_samples else 0
)

print(f"\nOverall accuracy: {overall:.2f}%")
print(f"\nTotal errors: {len(errors)}")
print(f"\nTotal samples evaluated: {valid_samples}")


# =========================
# SAMPLE ERRORS
# =========================
"""
Goal:
Show a small sample of mismatches for quick debugging.

Logic:
- Print only the first 5 errors
- Avoid flooding the console with too much output
"""

print("\n--- SAMPLE ERRORS ---")
for err in errors[:5]:
    print(err)
print("----------------------\n")


# =========================
# SAVE ERRORS
# =========================
"""
Goal:
Save all mismatches to a file for deeper analysis.

Logic:
- Store errors as JSON
- Keep formatting readable

indent=2:
→ makes the file easier for humans to read

ensure_ascii=False:
→ keeps special characters readable

Example:
errors.json → full list of mismatches
"""

with open("data/processed/errors.json", "w", encoding="utf-8") as f:
    json.dump(errors, f, indent=2, ensure_ascii=False)